[package]
name = "libakari"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
liboci-cli.workspace = true
oci-spec.workspace = true
serde.workspace = true
serde_json.workspace = true
tarpc.workspace = true
thiserror.workspace = true
