[package]
name = "akari"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
base64 = "0.22.0"
clap = { version = "4.5.4", features = ["derive"] }
liboci-cli = "0.3.2"
oci-spec = "0.6.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

icrate = { git = "https://github.com/retrage/objc2", branch = "icrate-virtualization", features = [
    "AppKit",
    "AppKit_all",
    "Foundation",
    "Foundation_all",
    "Virtualization",
    "Virtualization_all",
] }
objc2 = { git = "https://github.com/retrage/objc2", branch = "icrate-virtualization" }
block2 = { git = "https://github.com/retrage/objc2", branch = "icrate-virtualization" }

[[bin]]
name = "akari"

[[bin]]
name = "akari-vm"
