[workspace]
members = [
    "crates/agent",
    "crates/client",
    "crates/libakari",
    "crates/protos",
    "crates/server",
    "crates/shim",
    "crates/vmm",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.82"
async-trait = "0.1.80"
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
futures = "0.3"
futures-util = "0.3"
liboci-cli = "0.3.2"
log = "0.4.21"
oci-spec = "0.6.5"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
tarpc = { version = "0.34.0", features = [
    "serde-transport",
    "serde-transport-json",
    "unix",
] }
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["macros", "net", "rt-multi-thread"] }
ttrpc = { version = "0.8.1", features = ["async"] }
