[workspace]
members = [
    "crates/agent",
    "crates/client",
    "crates/libakari",
    "crates/protos",
    "crates/server",
    "crates/shim",
    "crates/vmm",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.83"
async-trait = "0.1.80"
clap = { version = "4.5.4", features = ["derive"] }
containerd-shim-protos = { version = "0.7.0", features = ["async"] }
containerd-shim = { version = "0.7.1", features = ["async"] }
env_logger = "0.11.3"
futures = "0.3"
futures-util = "0.3"
liboci-cli = "0.3.2"
log = "0.4.21"
oci-spec = "0.6.5"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
# tarpc = { version = "0.34.0", features = [
#     "serde-transport",
#     "serde-transport-json",
#     "unix",
# ] }
thiserror = "1.0.60"
tokio = { version = "1.37.0", features = ["macros", "net", "rt-multi-thread"] }
ttrpc = { version = "0.8.1", features = ["async"] }

# containerd-shim = { path = "../../../rust-extensions/crates/shim", features = [
#     "async",
# ] }
