[package]
name = "akari"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.0"
clap = { version = "4.4.8", features = ["derive"] }
daemonize = "0.5.0"
liboci-cli = "0.3.2"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"

icrate = { path = "../objc2/crates/icrate", features = [
    "AppKit",
    "AppKit_all",
    "Foundation",
    "Foundation_all",
    "Virtualization",
    "Virtualization_all",
] }
objc2 = { path = "../objc2/crates/objc2" }
block2 = { path = "../objc2/crates/block2" }
