name: Build
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

env:
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust components
        run: |
          rustup target add aarch64-apple-darwin
          rustup component add rust-src clippy rustfmt
      - name: Build (debug)
        run: cargo build
      - name: Build (release)
        run: cargo build --release
      - name: Clippy
        run: cargo clippy
      - name: Formatting
        run: cargo fmt --all -- --check
